### ISSUE TITLE
Tables only have left borders

### ISSUE THREAD

**Issue by parsiya** [parsiya/Hugo-Octopress#38]
The culprit is in the CSS. I have removed the right border to prevent it from being displayed when an overflow happens.

Change it back to `border` from `border-left`. [See]( https://github.com/parsiya/Hugo-Octopress/blob/master/static/css/hugo-octopress.css#L2135).

``` css
table,
th,
td
 {
    border-left: 1px solid black; /* remove the right border for when overflow happens */
    padding: 3px;
}
```
