### ISSUE TITLE
Submenu page

### ISSUE THREAD

**Issue by antaldaniel** [parsiya/Hugo-Octopress#55]
I had spent hours trying to find a working example of a Hugo theme that handles submenus, and a working example how to arrange the content so that I see a working submenu.  As far as I understand your theme handles submenues. 

Would it be possible to include an inserted submenu with a static page under the[ Individual Page 1 ](http://hugo-octopress-test.s3-website-us-east-1.amazonaws.com/page1/l)item?

**Comment by antaldaniel** [comment]
I was asking because as far as I read  your template it has submenus, but there were no examples.  I'll may give it a try, too.

**Comment by parsiya** [comment]
The theme does not have submenus. Neither in the navigation bar nor in the sidebar.

But to add submenus, you have to do something like this. The top menu gets an `identifier` field. This helps because you can later change the name of the menu w/o having to modify anything else.

``` toml
[[menu.sidebar]]
  Name = "External link to example.com"
  URL = "https://example.com"
  weight = 10
  identifier = "example"
```

Submenus are added normally with a `parent` field which points to the identifier of the parent.

``` toml
[[menu.sidebar]]
  Name = "submenu1"
  URL = "https://example.com"
  weight = 10
  parent = "example"

[[menu.sidebar]]
  Name = "submenu2"
  URL = "https://example.com"
  weight = 20
  parent = "example"
```
